/** Whether a mismatching snapshot is rewritten on disk or reported as a failure. */
export type SnapshotMode = 'write' | 'check';

/**
 * The task a check-mode failure tells the reader to run, when the caller names no other.
 *
 * Tier 2's, because every snapshot the shared engine was originally written for lives under
 * `test/output/` and is regenerated by that task.
 */
export const DEFAULT_UPDATE_COMMAND = 'deno task test:output';

/** Common options for the snapshot verification entry points. */
export type VerifyOptions = {
  /** Overrides the mode resolved from the environment. */
  mode?: SnapshotMode;
  /**
   * The `deno task` a check-mode failure tells the reader to run, defaulting to
   * {@link DEFAULT_UPDATE_COMMAND}.
   *
   * Exists because tier 3 reuses the same text-snapshot engine against a different snapshot root:
   * `deno task test:output` regenerates nothing under `test/compile/`, so pointing a tier-3 failure
   * at it sends the reader through a 22-second run that leaves the failure exactly as it was.
   */
  updateCommand?: string;
};

/**
 * Values of a boolean-ish environment variable that mean "off".
 *
 * Exported because more than one switch keys off `CI` the same way — {@link resolveSnapshotMode} here
 * and the Kotlin runner's Gradle work-dir mode — and two hand-rolled copies of this set would be free
 * to drift apart.
 */
export const FALSY_ENV_VALUES: ReadonlySet<string> = new Set(['', '0', 'false']);

/**
 * Resolves the snapshot mode from the environment.
 *
 * `GOAST_SNAPSHOT` wins when set. Otherwise the mode is `check` on CI and `write` everywhere else,
 * so that a local run updates snapshots and CI fails on drift.
 *
 * @param get Reads an environment variable. Injectable for tests.
 */
export function resolveSnapshotMode(
  get: (key: string) => string | undefined = (key) => Deno.env.get(key),
): SnapshotMode {
  const explicit = get('GOAST_SNAPSHOT');
  if (explicit === 'write' || explicit === 'check') return explicit;
  if (explicit !== undefined && explicit !== '') {
    throw new Error(`Invalid GOAST_SNAPSHOT value: "${explicit}". Expected "write" or "check".`);
  }

  const ci = get('CI');
  return ci !== undefined && !FALSY_ENV_VALUES.has(ci) ? 'check' : 'write';
}
